import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import { StoreProvider } from "@/store/StoreProvider";
import Navbar from "@/components/_components/Navbar";
const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${roboto.className} bg-gradient-to-bl from-cyan-400 to-indigo-600 
          dark:bg-gradient-to-r dark:from-slate-900 dark:to-slate-700`}
        >
          <Navbar />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
